### ISSUE TITLE
The small experiment in Figure 2

### ISSUE THREAD

**Issue by WN1695173791** [yang-song/score_sde_pytorch#3]
Hello, I want to realize the conversion of a one-dimensional non-normal distribution data into a standard distribution in Figure 2 of the paper. Could you give me some tips?

**Comment by WN1695173791** [comment]
If I take a color image through SDE and convert it to a standard distribution, can I display it through a 3D display?

**Comment by WN1695173791** [comment]
Whether or not I can transform one distribution into another particular distribution, it doesn't have to be the standard normal distribution

**Comment by AlbertLin0** [comment]
@WN1695173791 ，Hello, I also have the same question. Do you have any ideas?
