### ISSUE TITLE
Latent Code Manipulation

### ISSUE THREAD

**Issue by SidharthAgarwal18** [yang-song/score_sde_pytorch#5]
Hi, can someone tell me where is the code for "manipulation of latent representation". Like how did you where did you use interpolation and temperature change stuff
Thank you

**Comment by yang-song** [comment]
See [here](https://colab.research.google.com/drive/17lTrPLTt_0EDXa4hkbHmbAFQEkpRDZnh#scrollTo=oe3rLGRm28nc&line=1&uniqifier=1) for an example on manipulating latent representations. 

Note that typically (especially for large images) VP/subVP SDEs have better performance in latent code manipulation than VE SDEs.
