### ISSUE TITLE
Environment Setting and Dependencies

### ISSUE THREAD

**Issue by iamtonymwt** [yang-song/score_sde_pytorch#68]
Could anyone share a detailed requirements.txt and the Python version to run the code? Have spent several useless days.

**Comment by dummy-00** [comment]
你好，我想请问一下您弄出来了吗，可以分享一下嘛

**Comment by changshaow** [comment]
同问

**Comment by iamtonymwt** [comment]
> 你好，我想请问一下您弄出来了吗，可以分享一下嘛



> 同问

I shared it in an new issue.
